[package]
name = "cargo-pi"
version = "0.1.0"
description = "Sends compiled binaries to your raspberry Pis"
license = "MIT"
authors = ["llamicron <llamicron@gmail.com>"]
edition = "2018"

[dependencies]
